name: gate-failure-test
description: Test that a failing gate stops the pipeline

nodes:
  - id: create-bad-file
    type: task
    description: Create a file with invalid syntax
    command: echo "function test() { return 42" > bad.js
    
  - id: check-syntax
    type: gate
    description: Verify JavaScript syntax (should fail)
    command: node -c bad.js
    message: "JavaScript syntax check failed - pipeline stopped"
    
  - id: should-not-run
    type: task
    description: This should not execute
    command: echo "This should not appear"
