name: Type Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            runtime/package-lock.json
      - name: Install root dependencies
        run: npm ci
      - name: Install runtime dependencies
        run: npm ci
        working-directory: runtime
      - name: Run TypeScript type check
        run: npx tsc --noEmit
        working-directory: runtime
